/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sunrise.view.FormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.FormPanel',
 
    config: {
        itemId: 'registrationform',
		id: 'basicform',
        items: [
		{
                    docked: 'top',
                    xtype: 'titlebar',
                    title: 'Baithak Registration'
		},
            {
                xtype: 'fieldset',
               
                items: [
                    {
                        xtype: 'textfield',
                        label: 'First Name',
                        labelWrap: true,
                        name: 'FirstName',
                        placeHolder: 'Enter Your First Name'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Last Name',
                        labelWrap: true,
                        name: 'LastName',
                        placeHolder: 'Enter Your LastName'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        labelWrap: true,
                        name: 'Email',
                        placeHolder: 'email@example.com'
                    },
					{
                        xtype: 'textfield',
                        label: 'Occupation',
                        labelWrap: true,
                        name: 'Occupation',
                        placeHolder: 'Student'
                    },
                    {
                        xtype: 'numberfield',
                        label: 'Contact',
                        labelWrap: true,
                        name: 'Contact',
                        placeHolder: '8233899800'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Address',
                        labelWrap: true,
                        name: 'Address',
                        placeHolder: 'Enter Your Address'
                    }
						
                ]
            },{
							xtype: "panel",
							id: "output",
							label:"user response",
							scrollable: true,
							flex:0
					},
					{
							xtype: 'toolbar',
							layout: {
								pack: 'right'
							},
							ui: 'plain',
							items:
							[
								{
                           
                xtype: 'button',
                itemId: 'save',
				 ui: 'confirm',
               
                text: 'Submit'          		
									
								},
								{ 
								xtype: 'button',
								text: 'Reset',
								handler: function(){
								   Ext.getCmp('basicform').reset();
								}
								}
								
							]
						},
					
				
        ],
		listeners: [
            {
                fn: 'onFormSave',
                event: 'tap',
                delegate: '#save'
            }
			
        ]
    },
	onFormSave: function(button,e,options){
 
		var formObj = button.up('FormPanel');
		var formData = formObj.getValues();
		 
		var usr = Ext.create('Sunrise.model.User',{
			 FirstName: formData.FirstName,
			 LastName: formData.LastName,
			 Email:formData.Email,
			 Occupation:formData.Occupation,
			 Contact: formData.Contact,
			 Address: formData.Address
		});
		 
		var errs = usr.validate();
		var msg = '';
		 
		if (!errs.isValid()) {
		   errs.each(function (err) {
		   msg += err.getField() + ' : ' + err.getMessage() + '<br/>';
		   });
		 
		   Ext.Msg.alert('ERROR', msg);
		 
		} else {
		var request = {
							url: 'http://suryodaya.comyr.com/Register.php',
					       // url: 'http://localhost/touch-2.3.1/Sunrise/Register.php',
					        method: 'POST',

					// commenting this out will simply send this form with normal params
					// when this is true new HTML5 FormData object is created to send all fields
					                    xhr2: true,

					                    success: function(form, response) 
										{
						                   var out = Ext.getCmp("output");
						                   if(response) out.setHtml(response.message);
					                    },
					                 failure: function(form, response) {
						                    var out = Ext.getCmp("output");
						                        out.setHtml(response.message);
					                    }
				                       } ;
			 /*var userStore = Ext.getStore('userstore');
			 userStore.add(usr);
			 userStore.sync();*/
			 formObj.submit(request);
			 Ext.Msg.alert('SUCCESS', 'Data is send Successfully , Check your mail');
		}
 
	}
});